stages:
  - build
  - pages


build:
  stage: build
  image: node:lts
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ./node_modules
      - ./.yarn
      - ./.next/cache
  artifacts:
    paths:
      - .build/
    expire_in: 1 day    
  script:
    - export NEXT_TELEMETRY_DISABLED=1
    - ./.ci/build.sh

pages:
  stage: pages
  image:
    name: alpine:latest
    entrypoint: [""]
  cache: {}
  artifacts:
    paths:
      - public

  script:
    - ./.ci/ci-release.sh
    - ls -la public


  only:
    - main
